apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-oom
  namespace: default
  labels:
    app: nginx-oom
    incident: oomkilled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-oom
  template:
    metadata:
      labels:
        app: nginx-oom
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "5Mi"
          requests:
            memory: "5Mi"
        ports:
        - containerPort: 80