

grafana:
  adminPassword: "MySecurePassword"

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer

alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: kubetriage
    alertmanagerConfigNamespaceSelector: {}