# healthy.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubetriage
  name: kubetriage
  namespace: default
spec:
  serviceAccountName: kubetriage
  containers:
  - name: kubetriage
    image: simonangelfong/kubetriage:latest
    ports:
    - name: "http"   
      containerPort: 8000
      protocol: TCP
    env:
    - name: ANTHROPIC_API_KEY
      valueFrom:
        secretKeyRef:
          name: anthropic-api-key 
          key: anthropic_api_key
    - name: ANTHROPIC_MODEL
      valueFrom:
        secretKeyRef:
          name: anthropic-api-key 
          key: anthropic_model
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubetriage
  name: kubetriage
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: kubetriage
  ports:
  - name: "http"   
    port: 8000
    protocol: TCP
    targetPort: 8000