apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetriage-privileged
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubetriage-privileged
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubetriage-privileged-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubetriage
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubetriage-privileged