# healthy.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubetriage
  name: kubetriage
  namespace: default
spec:
  serviceAccountName: kubetriage
  containers:
  - name: kubetriage
    image: simonangelfong/kubetriage:function-calling
    ports:
    - name: "http"   
      containerPort: 8000
      protocol: TCP
    env:
    - name: ANTHROPIC_API_KEY
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: ANTHROPIC_API_KEY
    - name: ANTHROPIC_MODEL
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: ANTHROPIC_MODEL
    - name: SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: SMTP_HOST
    - name: SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: SMTP_PORT
    - name: SMTP_USER
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: SMTP_USER
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: SMTP_PASSWORD
    - name: NOTIFY_TO
      valueFrom:
        secretKeyRef:
          name: kubetriage-secrets
          key: NOTIFY_TO
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubetriage
  name: kubetriage
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: kubetriage
  ports:
  - name: "http"   
    port: 8000
    protocol: TCP
    targetPort: 8000