apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default        
  selector:
    matchLabels:
      app: nginx           
  endpoints:
    - port: http          
      interval: 15s
      path: /metrics